In [1]:
!pip install mglearn

   ---------------------------------------- 0.0/581.4 kB ? eta -:--:--
    --------------------------------------- 10.2/581.4 kB ? eta -:--:--
   -- ------------------------------------ 30.7/581.4 kB 435.7 kB/s eta 0:00:02
   ---- ---------------------------------- 71.7/581.4 kB 563.7 kB/s eta 0:00:01
   ---------------------------------------- 581.4/581.4 kB 3.7 MB/s eta 0:00:00


In [2]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
np.set_printoptions(precision=5)

import pandas as pd
pd.set_option('display.precision', 5)

In [3]:
import mglearn

In [4]:
X, y = mglearn.datasets.make_forge()

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=7, random_state=2021)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(y_test)

(19, 2) (19,)
(7, 2) (7,)
[1 0 1 0 1 1 0]


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2021)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(y_test)

(20, 2) (20,)
(6, 2) (6,)
[1 0 1 0 1 1]


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=2021)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(y_test)

(20, 2) (20,)
(6, 2) (6,)
[1 1 0 0 1 0]


In [9]:
pd.DataFrame({'X1': X[:,0],
              'X2': X[:,1],
              'Y': y}
            )

X1       X2  Y
0    9.96347  4.59677  1
1   11.03295 -0.16817  0
2   11.54156  5.21116  1
3    8.69289  1.54322  0
4    8.10623  4.28696  0
5    8.30989  4.80624  1
6   11.93027  4.64866  1
7    9.67285 -0.20283  0
8    8.34810  5.13416  1
9    8.67495  4.47573  1
10   9.17748  5.09283  1
11  10.24029  2.45544  1
12   8.68937  1.48710  0
13   8.92230 -0.63993  0
14   9.49123  4.33225  1
15   9.25694  5.13285  1
16   7.99815  4.85251  1
17   8.18378  1.29564  0
18   8.73371  2.49162  0
19   9.32298  5.09841  1
20  10.06394  0.99078  0
21   9.50049 -0.26430  0
22   8.34469  1.63824  0
23   9.50169  1.93825  0
24   9.15072  5.49832  1
25  11.56396  1.33894  0