In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
np.set_printoptions(precision=5)

import pandas as pd
pd.set_option('display.precision', 5)

In [2]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [4]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [5]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_train_hat = reg.predict(X_train)
print('train MAE: %.5f'%mean_absolute_error(y_train,y_train_hat))
print('train RMSE: %.5f'%mean_squared_error(y_train,y_train_hat)**0.5)
print('train R_square: %.5f'%r2_score(y_train,y_train_hat))

y_test_hat = reg.predict(X_test)
print('test MAE: %.5f'%mean_absolute_error(y_test,y_test_hat))
print('test RMSE: %.5f'%mean_squared_error(y_test,y_test_hat)**0.5)
print('test R_square: %.5f'%r2_score(y_test,y_test_hat))

train MAE: 0.41817
train RMSE: 0.50589
train R_square: 0.67009
test MAE: 0.49453
test RMSE: 0.62826
test R_square: 0.65934


In [6]:
pd.DataFrame({'X': X.ravel(),
              'Y': y}
            )

X        Y
0  -0.75276 -1.18073
1   2.70429  0.50016
2   1.39196  0.13773
3   0.59195  1.17396
4  -2.06389 -1.32036
5  -2.06403 -2.37365
6  -2.65150 -0.70117
7   2.19706  1.20320
8   0.60669  0.29263
9   1.24844  0.44972
10 -2.87649 -0.48647
11  2.81946  1.39516
12  1.99466  1.07384
13 -1.72597 -1.30838
14 -1.90905 -1.27708
15 -1.89957 -0.94576
16 -1.17455 -0.32691
17  0.14854  0.26134
18 -0.40833 -1.25636
19 -1.25263 -0.74647
20  0.67112  0.96251
21 -2.16304 -0.75241
22 -1.24713 -0.17851
23 -0.80183  0.13369
24 -0.26358 -0.38575
25  1.71106  0.79900
26 -1.80196 -1.11948
27  0.08541  0.97923
28  0.55449  0.65823
29 -2.72130 -0.08137
30  0.64527 -0.72143
31 -1.97686 -1.07676
32 -2.60969 -0.83685
33  2.69331  0.70946
34  2.79379  0.95082
35  1.85038  0.38110
36 -1.17232 -0.19613
37 -2.41397 -0.91391
38  1.10540  0.81264
39 -0.35909 -0.93416
40 -2.26777 -1.71132
41 -0.02894 -0.32310
42 -2.79367 -0.44713
43  2.45592  1.19813
44 -1.44732 -0.75151
45  0.97513  0.40012
46 -1.12973 -0.02566
47  0.12041  0.77614
48  0.28026  0.23938
49 -1.89087 -1.58832
50  2.81751  0.73141
51  1.65080  0.25093
52  2.63699  1.01581
53  2.36896  1.28948
54  0.58740  0.65213
55  2.53125  0.82614
56 -2.46904 -1.72409
57 -1.82410 -1.54665
58 -2.72864 -1.03732
59 -1.04802 -0.49132

In [7]:
print('w0: %.5f'%reg.intercept_)
print('w1: %.5f'%reg.coef_)

w0: -0.03180
w1: 0.39391


In [8]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
print(X.shape, y.shape)

(506, 104) (506,)


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [10]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [11]:
y_train_hat = reg.predict(X_train)
print('train MAE: %.5f'%mean_absolute_error(y_train,y_train_hat))
print('train RMSE: %.5f'%mean_squared_error(y_train,y_train_hat)**0.5)
print('train R_square: %.5f'%r2_score(y_train,y_train_hat))

y_test_hat = reg.predict(X_test)
print('test MAE: %.5f'%mean_absolute_error(y_test,y_test_hat))
print('test RMSE: %.5f'%mean_squared_error(y_test,y_test_hat)**0.5)
print('test R_square: %.5f'%r2_score(y_test,y_test_hat))

train MAE: 1.56741
train RMSE: 2.02246
train R_square: 0.95205
test MAE: 3.22590
test RMSE: 5.66296
test R_square: 0.60747


In [12]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
print(X.shape, y.shape)

(506, 104) (506,)


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [14]:
from sklearn.linear_model import Ridge
reg = Ridge(alpha=1)
reg.fit(X_train, y_train)

Ridge(alpha=1)

In [15]:
y_train_hat = reg.predict(X_train)
print('train MAE: %.5f'%mean_absolute_error(y_train,y_train_hat))
print('train RMSE: %.5f'%mean_squared_error(y_train,y_train_hat)**0.5)
print('train R_square: %.5f'%r2_score(y_train,y_train_hat))

y_test_hat = reg.predict(X_test)
print('test MAE: %.5f'%mean_absolute_error(y_test,y_test_hat))
print('test RMSE: %.5f'%mean_squared_error(y_test,y_test_hat)**0.5)
print('test R_square: %.5f'%r2_score(y_test,y_test_hat))

train MAE: 2.16564
train RMSE: 3.12130
train R_square: 0.88580
test MAE: 2.96269
test RMSE: 4.49428
test R_square: 0.75277


In [16]:
import mglearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [17]:
training_r2 = []
test_r2 = []

alpha_settings = [0, 0.1, 1, 10]
for alpha in alpha_settings:
    # build the model
    reg = Ridge(alpha=alpha)
    reg.fit(X_train, y_train)
    
    # r2 on the training set
    y_train_hat = reg.predict(X_train)
    training_r2.append(r2_score(y_train, y_train_hat))
    
    # r2 on the test set (generalization)
    y_test_hat = reg.predict(X_test)
    test_r2.append(r2_score(y_test, y_test_hat))

In [18]:
pd.DataFrame({'alpha': alpha_settings,
              'training R_square': training_r2,
              'test R_square': test_r2}
            )

alpha  training R_square  test R_square
0    0.0            0.95201        0.60296
1    0.1            0.92823        0.77221
2    1.0            0.88580        0.75277
3   10.0            0.78828        0.63594

In [19]:
import mglearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score

X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [20]:
num_vars = []
training_r2 = []
test_r2 = []

alpha_settings = [0.0001, 0.001, 0.01, 0.1, 1]
for alpha in alpha_settings:
    # build the model
    reg = Lasso(alpha=alpha, max_iter=1000)
    reg.fit(X_train, y_train)
    
    # no. features used
    num_vars.append(sum(reg.coef_ != 0))
    
    # r2 on the training set
    y_train_hat = reg.predict(X_train)
    training_r2.append(r2_score(y_train, y_train_hat))
    
    # r2 on the test set (generalization)
    y_test_hat = reg.predict(X_test)
    test_r2.append(r2_score(y_test, y_test_hat))

In [21]:
pd.DataFrame({'alpha': alpha_settings,
              'no. features used': num_vars,
              'training R_square': training_r2,
              'test R_square': test_r2}
            )

alpha  no. features used  training R_square  test R_square
0  0.0001                100            0.94209        0.69765
1  0.0010                 76            0.93546        0.75480
2  0.0100                 32            0.89611        0.76780
3  0.1000                  8            0.77100        0.63020
4  1.0000                  4            0.29324        0.20938

In [22]:
import mglearn
X, y = mglearn.datasets.make_forge()

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [24]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression()

In [25]:
y_test_hat = clf.predict(X_test)
print(y_test)
print(y_test_hat)

[1 0 1 0 1 1 0]
[1 0 1 0 1 0 0]


In [26]:
from sklearn.metrics import accuracy_score
print('test accuracy: %.5f'%accuracy_score(y_test, y_test_hat))

test accuracy: 0.85714


In [27]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)

In [28]:
training_accuracy = []
test_accuracy = []

C_settings = [0.01, 0.1, 1, 10, 100, 1000, 10000]
for C in C_settings:
    # build the model
    clf = LogisticRegression(C=C)
    clf.fit(X_train, y_train)
    
    # accuracy on the training set
    y_train_hat = clf.predict(X_train)
    training_accuracy.append(accuracy_score(y_train, y_train_hat))
    
    # accuracy on the test set (generalization)
    y_test_hat = clf.predict(X_test)
    test_accuracy.append(accuracy_score(y_test, y_test_hat))

In [29]:
pd.DataFrame({'C': C_settings,
              'training accuracy': training_accuracy,
              'test accuracy': test_accuracy}
            )

C  training accuracy  test accuracy
0      0.01            0.93427        0.93007
1      0.10            0.94131        0.95105
2      1.00            0.94366        0.96503
3     10.00            0.95775        0.95804
4    100.00            0.94601        0.95804
5   1000.00            0.94601        0.95804
6  10000.00            0.94601        0.96503

In [30]:
from sklearn.datasets import make_blobs
X, y = make_blobs(random_state=42)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [32]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(multi_class='ovr')
clf.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [33]:
y_test_hat = clf.predict(X_test)
print(y_test_hat)

[1 0 0 2 2 1 2 0 2 0 2 0 1 0 1 2 2 0 2 1 0 2 1 2 1]
