In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
np.set_printoptions(precision=5)

import pandas as pd
pd.set_option('display.precision', 5)

In [2]:
import mglearn, os

adult_path = os.path.join(mglearn.datasets.DATA_PATH, 'adult.data')
print(adult_path)

C:\ProgramData\anaconda3\Lib\site-packages\mglearn\data\adult.data


In [3]:
import pandas as pd

data = pd.read_csv(
    adult_path, header=None, index_col=False,
    names=['age', 'workclass', 'fnlwgt', 'education', 'education-num',
           'marital-status', 'occupation', 'relationship', 'race', 'gender',
           'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
           'income'])

display(data.head())

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race   gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [4]:
data = data[['age', 'workclass', 'education', 'gender', 'hours-per-week','occupation', 'income']]

display(data.head())

age          workclass   education   gender  hours-per-week  \
0   39          State-gov   Bachelors     Male              40   
1   50   Self-emp-not-inc   Bachelors     Male              13   
2   38            Private     HS-grad     Male              40   
3   53            Private        11th     Male              40   
4   28            Private   Bachelors   Female              40   

           occupation  income  
0        Adm-clerical   <=50K  
1     Exec-managerial   <=50K  
2   Handlers-cleaners   <=50K  
3   Handlers-cleaners   <=50K  
4      Prof-specialty   <=50K

In [5]:
print(data.income.value_counts())

income
<=50K    24720
>50K      7841
Name: count, dtype: int64


In [6]:
print(data.gender.value_counts())

gender
Male      21790
Female    10771
Name: count, dtype: int64


In [7]:
print(data.workclass.value_counts())

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64


In [8]:
data_dummies = pd.get_dummies(data)

display(data_dummies.head())

age  hours-per-week  workclass_ ?  workclass_ Federal-gov  \
0   39              40         False                   False   
1   50              13         False                   False   
2   38              40         False                   False   
3   53              40         False                   False   
4   28              40         False                   False   

   workclass_ Local-gov  workclass_ Never-worked  workclass_ Private  \
0                 False                    False               False   
1                 False                    False               False   
2                 False                    False                True   
3                 False                    False                True   
4                 False                    False                True   

   workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  workclass_ State-gov  \
0                    False                        False                  True   
1                    False                         True                 False   
2                    False                        False                 False   
3                    False                        False                 False   
4                    False                        False                 False   

   ...  occupation_ Machine-op-inspct  occupation_ Other-service  \
0  ...                          False                      False   
1  ...                          False                      False   
2  ...                          False                      False   
3  ...                          False                      False   
4  ...                          False                      False   

   occupation_ Priv-house-serv  occupation_ Prof-specialty  \
0                        False                       False   
1                        False                       False   
2                        False                       False   
3                        False                       False   
4                        False                        True   

   occupation_ Protective-serv  occupation_ Sales  occupation_ Tech-support  \
0                        False              False                     False   
1                        False              False                     False   
2                        False              False                     False   
3                        False              False                     False   
4                        False              False                     False   

   occupation_ Transport-moving  income_ <=50K  income_ >50K  
0                         False           True         False  
1                         False           True         False  
2                         False           True         False  
3                         False           True         False  
4                         False           True         False  

[5 rows x 46 columns]

In [9]:
X = data_dummies.loc[:, 'age':'occupation_ Transport-moving'].values
y = data_dummies['income_ >50K'].values

print('X.shape: {} y.shape: {}'.format(X.shape, y.shape))

X.shape: (32561, 44) y.shape: (32561,)


In [10]:
data_dummies = pd.get_dummies(data, columns=['age','workclass'])

display(data_dummies.head())

education   gender  hours-per-week          occupation  income  age_17  \
0   Bachelors     Male              40        Adm-clerical   <=50K   False   
1   Bachelors     Male              13     Exec-managerial   <=50K   False   
2     HS-grad     Male              40   Handlers-cleaners   <=50K   False   
3        11th     Male              40   Handlers-cleaners   <=50K   False   
4   Bachelors   Female              40      Prof-specialty   <=50K   False   

   age_18  age_19  age_20  age_21  ...  age_90  workclass_ ?  \
0   False   False   False   False  ...   False         False   
1   False   False   False   False  ...   False         False   
2   False   False   False   False  ...   False         False   
3   False   False   False   False  ...   False         False   
4   False   False   False   False  ...   False         False   

   workclass_ Federal-gov  workclass_ Local-gov  workclass_ Never-worked  \
0                   False                 False                    False   
1                   False                 False                    False   
2                   False                 False                    False   
3                   False                 False                    False   
4                   False                 False                    False   

   workclass_ Private  workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  \
0               False                    False                        False   
1               False                    False                         True   
2                True                    False                        False   
3                True                    False                        False   
4                True                    False                        False   

   workclass_ State-gov  workclass_ Without-pay  
0                  True                   False  
1                 False                   False  
2                 False                   False  
3                 False                   False  
4                 False                   False  

[5 rows x 87 columns]

In [11]:
import mglearn

X, y = mglearn.datasets.make_wave(n_samples=100)
print(X[:5])

[[-0.75276]
 [ 2.70429]
 [ 1.39196]
 [ 0.59195]
 [-2.06389]]


In [12]:
import numpy as np

bins = np.linspace(-3, 3, 11)
print('bins: {}'.format(bins))
which_bin = np.digitize(X, bins=bins)

bins: [-3.  -2.4 -1.8 -1.2 -0.6  0.   0.6  1.2  1.8  2.4  3. ]


In [13]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(which_bin)
X_binned = encoder.transform(which_bin)
print(X_binned[:5])

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
from sklearn.linear_model import LinearRegression
reg_lr = LinearRegression().fit(X, y)
reg_lr_bin = LinearRegression().fit(X_binned, y)

from sklearn.tree import DecisionTreeRegressor
reg_dt = DecisionTreeRegressor(min_samples_split=3).fit(X, y)
reg_dt_bin = DecisionTreeRegressor(min_samples_split=3).fit(X_binned, y)

In [15]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=100)
print(X[:5])

[[-0.75276]
 [ 2.70429]
 [ 1.39196]
 [ 0.59195]
 [-2.06389]]


In [16]:
from sklearn.preprocessing import PolsnomialFeatures
poly = PolynomialFeatures(degree=3, include_bias=False)
poly.fit(X)
poly.get_feature_names_out()

array(['x0', 'x0^2', 'x0^3'], dtype=object)

In [17]:
X_poly = poly.transform(X)
print(X_poly[:5])

[[-0.75276  0.56665 -0.42655]
 [ 2.70429  7.31316 19.77688]
 [ 1.39196  1.93756  2.69702]
 [ 0.59195  0.35041  0.20742]
 [-2.06389  4.25963 -8.79141]]


In [18]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, random_state=0)

In [19]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
clf = LogisticRegression()
clf.fit(X_train_scaled, y_train)

LogisticRegression()

In [21]:
y_train_hat = clf.predict(X_train_scaled)
print('train accuracy: %.5f'%accuracy_score(y_train, y_train_hat))

y_test_hat = clf.predict(X_test_scaled)
print('test accuracy: %.5f'%accuracy_score(y_test, y_test_hat))

train accuracy: 0.97321
test accuracy: 0.97368


In [22]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, random_state=42)

In [23]:
poly = PolynomialFeatures(degree=2, include_bias=False)
poly.fit(X_train)
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x3', 'x0^2', 'x0 x1', 'x0 x2', 'x0 x3', 'x1^2',
       'x1 x2', 'x1 x3', 'x2^2', 'x2 x3', 'x3^2'], dtype=object)

In [24]:
X_train_poly = poly.transform(X_train)
X_test_poly = poly.transform(X_test)
print(X_train.shape, X_train_poly.shape)

(112, 4) (112, 14)


In [25]:
scaler = StandardScaler()
scaler.fit(X_train_poly)
X_train_poly_scaled = scaler.transform(X_train_poly)
X_test_poly_scaled = scaler.transform(X_test_poly)

In [26]:
clf = LogisticRegression()
clf.fit(X_train_poly_scaled, y_train)

LogisticRegression()

In [27]:
y_train_hat = clf.predict(X_train_poly_scaled)
print('train accuracy: %.5f'%accuracy_score(y_train, y_train_hat))

y_test_hat = clf.predict(X_test_poly_scaled)
print('test accuracy: %.5f'%accuracy_score(y_test, y_test_hat))

train accuracy: 0.97321
test accuracy: 1.00000


In [28]:
import numpy as np

X_train_log = np.log(X_train + 1)
X_test_log = np.log(X_test + 1)

X_train_rec = np.exp(X_train_log) - 1
X_test_rec = np.exp(X_test_log) - 1

In [29]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=66)

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train.shape

(426, 30)

In [30]:
clf = KNeighborsClassifier()
clf.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [31]:
y_train_hat = clf.predict(X_train_scaled)
print('train accuracy: %.5f'%accuracy_score(y_train, y_train_hat))

y_test_hat = clf.predict(X_test_scaled)
print('test accuracy: %.5f'%accuracy_score(y_test, y_test_hat))

train accuracy: 0.98122
test accuracy: 0.95804


In [32]:
from sklearn.feature_selection import SelectKBest, f_classif

select = SelectKBest(f_classif, k=20)
select.fit(X_train_scaled, y_train)
print(select.scores_)

[4.83463e+02 7.30185e+01 5.28179e+02 4.47936e+02 8.31685e+01 2.82588e+02
 4.03951e+02 6.77339e+02 6.14527e+01 6.01858e-01 2.31866e+02 1.04667e+00
 2.34006e+02 2.98128e+02 1.51979e+00 4.25157e+01 2.41668e+01 7.54075e+01
 4.75615e-03 2.31919e+00 6.53070e+02 1.08040e+02 7.04457e+02 5.24964e+02
 1.37074e+02 2.95079e+02 3.73197e+02 7.97342e+02 1.26635e+02 7.49205e+01]


In [33]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif

select = SelectKBest(mutual_info_classif, k=20)
select.fit(X_train_scaled, y_train)
print(select.scores_)

[0.37652 0.06112 0.3945  0.36256 0.07151 0.25488 0.39395 0.42784 0.0685
 0.00649 0.23857 0.      0.24569 0.33068 0.      0.06884 0.15362 0.0881
 0.02172 0.04572 0.46291 0.11179 0.49036 0.46999 0.12156 0.28613 0.32562
 0.46268 0.14626 0.0902 ]


In [34]:
from sklearn.feature_selection import SelectKBest, f_classif

select = SelectKBest(f_classif, k=20)
select.fit(X_train_scaled, y_train)
X_train_selected = select.transform(X_train_scaled)
X_test_selected = select.transform(X_test_scaled)

In [35]:
clf = KNeighborsClassifier()
clf.fit(X_train_selected, y_train)

KNeighborsClassifier()

In [36]:
y_train_hat = clf.predict(X_train_selected)
print('train accuracy: %.5f'%accuracy_score(y_train, y_train_hat))
                                         
y_test_hat = clf.predict(X_test_selected)
print('test accuracy: %.5f'%accuracy_score(y_test, y_test_hat))

train accuracy: 0.98826
test accuracy: 0.97902


In [37]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVC

estimator = SVC(kernel='linear')
select = RFE(estimator, n_features_to_select=10, step=1)
select.fit(X_train_scaled, y_train)

X_train_selected = select.transform(X_train_scaled)
X_test_selected = select.transform(X_test_scaled)
select.get_support()

array([False, False, False, False, False, False, False,  True, False,
        True, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True,  True, False,  True,
       False,  True, False])

In [38]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVC

estimator = SVC(kernel='linear')
select = RFE(estimator, n_features_to_select=20, step=1)
select.fit(X_train_scaled, y_train)

X_train_selected = select.transform(X_train_scaled)
X_test_selected = select.transform(X_test_scaled)
select.get_support()

array([False, False,  True, False, False, False,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True])

In [39]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier

fmodel = RandomForestClassifier()
select = SelectFromModel(fmodel, threshold='mean')
select.fit(X_train, y_train)

X_train_selected = select.transform(X_train)
X_test_selected = select.transform(X_test)
select.get_support()

array([ True, False,  True,  True, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True,  True, False, False, False,
        True, False, False])

In [40]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression

fmodel = LogisticRegression()
select = SelectFromModel(fmodel, max_features=10)
select.fit(X_train_scaled, y_train)

X_train_selected = select.transform(X_train_scaled)
X_test_selected = select.transform(X_test_scaled)
select.get_support()

array([False, False, False, False, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True,  True,  True,  True,  True, False, False, False,
        True,  True, False])

In [41]:
from sklearn.ensemble import RandomForestClassifier

fmodel = RandomForestClassifier()
fmodel.fit(X_train, y_train)
fmodel.feature_importances_

array([0.06073, 0.01539, 0.0757 , 0.01868, 0.00567, 0.01795, 0.04973,
       0.08599, 0.00298, 0.00344, 0.01433, 0.00382, 0.01543, 0.0346 ,
       0.0034 , 0.0046 , 0.00892, 0.00363, 0.0022 , 0.00716, 0.08641,
       0.01641, 0.12109, 0.09249, 0.01723, 0.01794, 0.02693, 0.16962,
       0.01066, 0.00685])

In [42]:
from sklearn.feature_selection import SelectFromModel

select = SelectFromModel(fmodel, prefit=True, threshold='mean')
X_train_selected = select.transform(X_train)
X_test_selected = select.transform(X_test)
select.get_support()

array([ True, False,  True, False, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True,  True, False, False, False,
        True, False, False])